version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: yourdb
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  server:
    build: ./services/server
    ports:
      - "8000:8000"

  crawler:
    build: ./services/crawler
    ports:
      - "8001:8001"

  recommendation:
    build: ./services/recommendation_system
    ports:
      - "8002:8002"
  
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: INTERNAL://kafka:9093,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9093,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: INTERNAL
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - ./data/kafka:/tmp/kraft-combined-logs

  proxy:
    build:
      context: ./services/proxy
    ports:
      - "50051:50051"
    depends_on:
      - kafka

  vectorstore-card:
    build:
      context: ./vectorstore
      dockerfile: Dockerfile.card
    ports:
      - "60051:60051"

  vectorstore-deck:
    build:
      context: ./vectorstore
      dockerfile: Dockerfile.deck
    ports:
      - "60052:60051"