// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: search.proto

package search

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Input message: a list of cards (can be grouped or full deck)
type VectorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []string               `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorRequest) Reset() {
	*x = VectorRequest{}
	mi := &file_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorRequest) ProtoMessage() {}

func (x *VectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorRequest.ProtoReflect.Descriptor instead.
func (*VectorRequest) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{0}
}

func (x *VectorRequest) GetCards() []string {
	if x != nil {
		return x.Cards
	}
	return nil
}

// Response message for card similarity
type CardResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []string               `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardResult) Reset() {
	*x = CardResult{}
	mi := &file_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardResult) ProtoMessage() {}

func (x *CardResult) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardResult.ProtoReflect.Descriptor instead.
func (*CardResult) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{1}
}

func (x *CardResult) GetCards() []string {
	if x != nil {
		return x.Cards
	}
	return nil
}

// Response message for deck similarity
type DeckResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decks         []string               `protobuf:"bytes,1,rep,name=decks,proto3" json:"decks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeckResult) Reset() {
	*x = DeckResult{}
	mi := &file_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckResult) ProtoMessage() {}

func (x *DeckResult) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckResult.ProtoReflect.Descriptor instead.
func (*DeckResult) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{2}
}

func (x *DeckResult) GetDecks() []string {
	if x != nil {
		return x.Decks
	}
	return nil
}

var File_search_proto protoreflect.FileDescriptor

const file_search_proto_rawDesc = "" +
	"\n" +
	"\fsearch.proto\x12\x06search\"%\n" +
	"\rVectorRequest\x12\x14\n" +
	"\x05cards\x18\x01 \x03(\tR\x05cards\"\"\n" +
	"\n" +
	"CardResult\x12\x14\n" +
	"\x05cards\x18\x01 \x03(\tR\x05cards\"\"\n" +
	"\n" +
	"DeckResult\x12\x14\n" +
	"\x05decks\x18\x01 \x03(\tR\x05decks2\x91\x01\n" +
	"\rVectorService\x12?\n" +
	"\x12SearchSimilarCards\x12\x15.search.VectorRequest\x1a\x12.search.CardResult\x12?\n" +
	"\x12SearchSimilarDecks\x12\x15.search.VectorRequest\x1a\x12.search.DeckResultB\\ZZgithub.com/Khiem17204/go_recommendation_system/services/recommendation_system/proto/searchb\x06proto3"

var (
	file_search_proto_rawDescOnce sync.Once
	file_search_proto_rawDescData []byte
)

func file_search_proto_rawDescGZIP() []byte {
	file_search_proto_rawDescOnce.Do(func() {
		file_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_search_proto_rawDesc), len(file_search_proto_rawDesc)))
	})
	return file_search_proto_rawDescData
}

var file_search_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_search_proto_goTypes = []any{
	(*VectorRequest)(nil), // 0: search.VectorRequest
	(*CardResult)(nil),    // 1: search.CardResult
	(*DeckResult)(nil),    // 2: search.DeckResult
}
var file_search_proto_depIdxs = []int32{
	0, // 0: search.VectorService.SearchSimilarCards:input_type -> search.VectorRequest
	0, // 1: search.VectorService.SearchSimilarDecks:input_type -> search.VectorRequest
	1, // 2: search.VectorService.SearchSimilarCards:output_type -> search.CardResult
	2, // 3: search.VectorService.SearchSimilarDecks:output_type -> search.DeckResult
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_search_proto_init() }
func file_search_proto_init() {
	if File_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_search_proto_rawDesc), len(file_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_search_proto_goTypes,
		DependencyIndexes: file_search_proto_depIdxs,
		MessageInfos:      file_search_proto_msgTypes,
	}.Build()
	File_search_proto = out.File
	file_search_proto_goTypes = nil
	file_search_proto_depIdxs = nil
}
