// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: cards_in_deck.sql

package db

import (
	"context"
	"database/sql"
)

const addCardToDeck = `-- name: AddCardToDeck :one
INSERT INTO cards_in_deck (
    card_id,
    deck_id
) VALUES (
    $1,
    $2
) RETURNING id, card_id, deck_id
`

type AddCardToDeckParams struct {
	CardID sql.NullInt64 `json:"card_id"`
	DeckID sql.NullInt64 `json:"deck_id"`
}

func (q *Queries) AddCardToDeck(ctx context.Context, arg AddCardToDeckParams) (CardsInDeck, error) {
	row := q.db.QueryRowContext(ctx, addCardToDeck, arg.CardID, arg.DeckID)
	var i CardsInDeck
	err := row.Scan(&i.ID, &i.CardID, &i.DeckID)
	return i, err
}

const countCardInDeck = `-- name: CountCardInDeck :one
SELECT COUNT(*) FROM cards_in_deck
WHERE card_id = $1 AND deck_id = $2
`

type CountCardInDeckParams struct {
	CardID sql.NullInt64 `json:"card_id"`
	DeckID sql.NullInt64 `json:"deck_id"`
}

func (q *Queries) CountCardInDeck(ctx context.Context, arg CountCardInDeckParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCardInDeck, arg.CardID, arg.DeckID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAllCardsFromDeck = `-- name: DeleteAllCardsFromDeck :exec
DELETE FROM cards_in_deck
WHERE deck_id = $1
`

func (q *Queries) DeleteAllCardsFromDeck(ctx context.Context, deckID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, deleteAllCardsFromDeck, deckID)
	return err
}

const deleteAllDecksFromCard = `-- name: DeleteAllDecksFromCard :exec
DELETE FROM cards_in_deck
WHERE card_id = $1
`

func (q *Queries) DeleteAllDecksFromCard(ctx context.Context, cardID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, deleteAllDecksFromCard, cardID)
	return err
}

const deleteCardFromDeck = `-- name: DeleteCardFromDeck :exec
DELETE FROM cards_in_deck
WHERE card_id = $1 AND deck_id = $2
`

type DeleteCardFromDeckParams struct {
	CardID sql.NullInt64 `json:"card_id"`
	DeckID sql.NullInt64 `json:"deck_id"`
}

func (q *Queries) DeleteCardFromDeck(ctx context.Context, arg DeleteCardFromDeckParams) error {
	_, err := q.db.ExecContext(ctx, deleteCardFromDeck, arg.CardID, arg.DeckID)
	return err
}

const getCardsFromDeck = `-- name: GetCardsFromDeck :many
SELECT id, card_id, deck_id FROM cards_in_deck
WHERE deck_id = $1
`

func (q *Queries) GetCardsFromDeck(ctx context.Context, deckID sql.NullInt64) ([]CardsInDeck, error) {
	rows, err := q.db.QueryContext(ctx, getCardsFromDeck, deckID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CardsInDeck{}
	for rows.Next() {
		var i CardsInDeck
		if err := rows.Scan(&i.ID, &i.CardID, &i.DeckID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDecksFromCard = `-- name: GetDecksFromCard :many
SELECT id, card_id, deck_id FROM cards_in_deck
WHERE card_id = $1
`

func (q *Queries) GetDecksFromCard(ctx context.Context, cardID sql.NullInt64) ([]CardsInDeck, error) {
	rows, err := q.db.QueryContext(ctx, getDecksFromCard, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CardsInDeck{}
	for rows.Next() {
		var i CardsInDeck
		if err := rows.Scan(&i.ID, &i.CardID, &i.DeckID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
