# card-crawler-job.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: card-crawler-job
spec:
  schedule: "0 0 * * 0"  # Every Sunday at 00:00
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: card-crawler
            image: go-recommendation-system/crawler:latest
            imagePullPolicy: IfNotPresent
            command: ["./crawler"]
            args: ["--mode", "card"]
            env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_NAME
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
            resources:
              requests:
                memory: "256Mi"
                cpu: "250m"
              limits:
                memory: "512Mi"
                cpu: "500m"
          restartPolicy: OnFailure
