# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import search_pb2 as search__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in search_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VectorServiceStub(object):
    """The vector store service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchSimilarCards = channel.unary_unary(
                '/search.VectorService/SearchSimilarCards',
                request_serializer=search__pb2.VectorRequest.SerializeToString,
                response_deserializer=search__pb2.CardResult.FromString,
                _registered_method=True)
        self.SearchSimilarDecks = channel.unary_unary(
                '/search.VectorService/SearchSimilarDecks',
                request_serializer=search__pb2.VectorRequest.SerializeToString,
                response_deserializer=search__pb2.DeckResult.FromString,
                _registered_method=True)


class VectorServiceServicer(object):
    """The vector store service definition
    """

    def SearchSimilarCards(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchSimilarDecks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VectorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchSimilarCards': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchSimilarCards,
                    request_deserializer=search__pb2.VectorRequest.FromString,
                    response_serializer=search__pb2.CardResult.SerializeToString,
            ),
            'SearchSimilarDecks': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchSimilarDecks,
                    request_deserializer=search__pb2.VectorRequest.FromString,
                    response_serializer=search__pb2.DeckResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'search.VectorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('search.VectorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VectorService(object):
    """The vector store service definition
    """

    @staticmethod
    def SearchSimilarCards(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.VectorService/SearchSimilarCards',
            search__pb2.VectorRequest.SerializeToString,
            search__pb2.CardResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchSimilarDecks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.VectorService/SearchSimilarDecks',
            search__pb2.VectorRequest.SerializeToString,
            search__pb2.DeckResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
