# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: search.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'search.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csearch.proto\x12\x06search\"\x1e\n\rVectorRequest\x12\r\n\x05\x63\x61rds\x18\x01 \x03(\t\"\x1b\n\nCardResult\x12\r\n\x05\x63\x61rds\x18\x01 \x03(\t\"\x1b\n\nDeckResult\x12\r\n\x05\x64\x65\x63ks\x18\x01 \x03(\t2\x91\x01\n\rVectorService\x12?\n\x12SearchSimilarCards\x12\x15.search.VectorRequest\x1a\x12.search.CardResult\x12?\n\x12SearchSimilarDecks\x12\x15.search.VectorRequest\x1a\x12.search.DeckResultB\\ZZgithub.com/Khiem17204/go_recommendation_system/services/recommendation_system/proto/searchb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZZgithub.com/Khiem17204/go_recommendation_system/services/recommendation_system/proto/search'
  _globals['_VECTORREQUEST']._serialized_start=24
  _globals['_VECTORREQUEST']._serialized_end=54
  _globals['_CARDRESULT']._serialized_start=56
  _globals['_CARDRESULT']._serialized_end=83
  _globals['_DECKRESULT']._serialized_start=85
  _globals['_DECKRESULT']._serialized_end=112
  _globals['_VECTORSERVICE']._serialized_start=115
  _globals['_VECTORSERVICE']._serialized_end=260
# @@protoc_insertion_point(module_scope)
